Fixed active wait

diff --git a/buildkitd b/buildkitd
--- a/buildkitd
+++ b/buildkitd
@@ -79,7 +79,13 @@ start() {
     check_volume
     docker pull "moby/buildkit:${BUILDKIT_VERSION}"
     docker run -d --privileged --rm -p "${BUILDKIT_PORT}:${BUILDKIT_PORT}" --mount source="${BUILDKIT_VOLUMENAME}",target=/var/lib/buildkit "moby/buildkit:${BUILDKIT_VERSION}" --addr "${BUILDKIT_HOST}" "$@"
-    timeout 60s /bin/bash -c "while ! status 2> /dev/null; do sleep 1; done"
+    echo -n "Buildkitd is starting @ ${BUILDKIT_HOST}"
+    timeout 60s /bin/bash -c "while ! \"${SCRIPT_FOLDER}/buildkitd\" status 2> /dev/null; do sleep 1; echo -n '.'; done"
+    echo
+    if ! status 2> /dev/null; then
+      echo "ERROR: impossible to start buildkitd  @ ${BUILDKIT_HOST}!"
+      exit 1
+    fi
   else 
     >&2 echo "WARNING: buildkitd is already running @ ${BUILDKIT_HOST}!"
   fi
@@ -110,7 +116,7 @@ lock() {
     sleep 1
   done
   echo 1 > "${lockfile}"
-  trap 'unlock '"${1}" EXIT
+  trap 'unlock '"${1}" EXIT SIGINT SIGTERM
 }
 
 unlock() {
